services:
  online-cv-api_dev:
    environment:
      - GITHUB_TOKEN
    container_name: online-cv-api_dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 3000:3000